// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFc6AL2t4EVCL9hMWjnNxvWO0-1WBp1lI',
    appId: '1:841974142704:web:061dc3037c5d0e9cfb9435',
    messagingSenderId: '841974142704',
    projectId: 'crowdsourced-sound-labelling',
    authDomain: 'crowdsourced-sound-labelling.firebaseapp.com',
    storageBucket: 'crowdsourced-sound-labelling.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3soGIgPl9Nvp1aa87qVX8t_q-jGdsJo',
    appId: '1:841974142704:android:0b0b00d400cb9139fb9435',
    messagingSenderId: '841974142704',
    projectId: 'crowdsourced-sound-labelling',
    storageBucket: 'crowdsourced-sound-labelling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzjsAik5GrQi2BX0JP8v-T6Rveu8fke4w',
    appId: '1:841974142704:ios:1f4eac2f420189f0fb9435',
    messagingSenderId: '841974142704',
    projectId: 'crowdsourced-sound-labelling',
    storageBucket: 'crowdsourced-sound-labelling.firebasestorage.app',
    iosBundleId: 'com.forestsoundplatform.flutterApp',
  );
}
